// Genere depuis .canevas/project/B1-personnages.dc.html : ne pas redessiner.
// Poses de profil tournees vers la droite, pieds a l'origine 0,0.
// {L} marque la place des lunettes de Jean.
// Seule retouche : dans poutre-epaule, la poutre est isolee dans le groupe
// .poutre-lance (origine au centre de la poutre), sans changer le dessin.

export const POSES = {
  'debout':
    '<polyline class="se" points="-2,-56 -2,-4 3,-4" fill="none" stroke-width="8" stroke-linecap="round" stroke-linejoin="round"/><polyline class="se" points="2,-56 2,-4 7,-4" fill="none" stroke-width="8" stroke-linecap="round" stroke-linejoin="round"/><polyline class="se" points="0,-89 -2,-58" fill="none" stroke-width="7" stroke-linecap="round" stroke-linejoin="round"/><rect class="fe" x="-9" y="-97" width="18" height="45" rx="9"/><circle class="fe" cx="1" cy="-110" r="10"/>{L}<polyline class="si" points="1,-89 3,-58" fill="none" stroke-width="10" stroke-linecap="round" stroke-linejoin="round"/><polyline class="se" points="1,-89 3,-58" fill="none" stroke-width="7" stroke-linecap="round" stroke-linejoin="round"/>',
  'marche-1':
    '<polyline class="se" points="-1,-56 -12,-9 -7,-4" fill="none" stroke-width="8" stroke-linecap="round" stroke-linejoin="round"/><polyline class="se" points="1,-56 13,-4 18,-8" fill="none" stroke-width="8" stroke-linecap="round" stroke-linejoin="round"/><polyline class="se" points="0,-89 11,-62" fill="none" stroke-width="7" stroke-linecap="round" stroke-linejoin="round"/><rect class="fe" x="-9" y="-97" width="18" height="45" rx="9"/><circle class="fe" cx="1" cy="-110" r="10"/>{L}<polyline class="si" points="1,-89 -11,-61" fill="none" stroke-width="10" stroke-linecap="round" stroke-linejoin="round"/><polyline class="se" points="1,-89 -11,-61" fill="none" stroke-width="7" stroke-linecap="round" stroke-linejoin="round"/>',
  'marche-2':
    '<polyline class="se" points="-1,-56 0,-4 5,-4" fill="none" stroke-width="8" stroke-linecap="round" stroke-linejoin="round"/><polyline class="se" points="1,-56 8,-32 3,-13 8,-12" fill="none" stroke-width="8" stroke-linecap="round" stroke-linejoin="round"/><polyline class="se" points="0,-89 -3,-58" fill="none" stroke-width="7" stroke-linecap="round" stroke-linejoin="round"/><rect class="fe" x="-9" y="-97" width="18" height="45" rx="9"/><circle class="fe" cx="1" cy="-110" r="10"/>{L}<polyline class="si" points="1,-89 5,-58" fill="none" stroke-width="10" stroke-linecap="round" stroke-linejoin="round"/><polyline class="se" points="1,-89 5,-58" fill="none" stroke-width="7" stroke-linecap="round" stroke-linejoin="round"/>',
  'penche':
    '<polyline class="se" points="-5,-56 -6,-4 -1,-4" fill="none" stroke-width="8" stroke-linecap="round" stroke-linejoin="round"/><polyline class="se" points="-1,-56 1,-4 6,-4" fill="none" stroke-width="8" stroke-linecap="round" stroke-linejoin="round"/><polyline class="se" points="14.4,-84.1 32,-60" fill="none" stroke-width="7" stroke-linecap="round" stroke-linejoin="round"/><g transform="translate(-3 0) rotate(30 0 -56)"><rect class="fe" x="-9" y="-97" width="18" height="45" rx="9"/><circle class="fe" cx="1" cy="-110" r="10"/>{L}</g><polyline class="si" points="14.4,-84.1 29,-59.5" fill="none" stroke-width="10" stroke-linecap="round" stroke-linejoin="round"/><polyline class="se" points="14.4,-84.1 29,-59.5" fill="none" stroke-width="7" stroke-linecap="round" stroke-linejoin="round"/>',
  'bras-tendus':
    '<polyline class="se" points="-2,-56 -2,-4 3,-4" fill="none" stroke-width="8" stroke-linecap="round" stroke-linejoin="round"/><polyline class="se" points="2,-56 2,-4 7,-4" fill="none" stroke-width="8" stroke-linecap="round" stroke-linejoin="round"/><polyline class="se" points="0,-89 31,-76" fill="none" stroke-width="7" stroke-linecap="round" stroke-linejoin="round"/><rect class="fe" x="-9" y="-97" width="18" height="45" rx="9"/><circle class="fe" cx="1" cy="-110" r="10"/>{L}<polyline class="si" points="1,-89 29,-73" fill="none" stroke-width="10" stroke-linecap="round" stroke-linejoin="round"/><polyline class="se" points="1,-89 29,-73" fill="none" stroke-width="7" stroke-linecap="round" stroke-linejoin="round"/>',
  'plan-sous-bras':
    '<polyline class="se" points="-2,-56 -2,-4 3,-4" fill="none" stroke-width="8" stroke-linecap="round" stroke-linejoin="round"/><polyline class="se" points="2,-56 2,-4 7,-4" fill="none" stroke-width="8" stroke-linecap="round" stroke-linejoin="round"/><polyline class="se" points="0,-89 -3,-58" fill="none" stroke-width="7" stroke-linecap="round" stroke-linejoin="round"/><rect class="fe" x="-9" y="-97" width="18" height="45" rx="9"/><circle class="fe" cx="1" cy="-110" r="10"/>{L}<rect class="fi sa" x="-16" y="-80" width="44" height="9" rx="4.5" stroke-width="1.8"/><circle class="sa" cx="23.5" cy="-75.5" r="2.2" fill="none" stroke-width="1.2"/><polyline class="si" points="1,-89 0,-67 14,-68" fill="none" stroke-width="10" stroke-linecap="round" stroke-linejoin="round"/><polyline class="se" points="1,-89 0,-67 14,-68" fill="none" stroke-width="7" stroke-linecap="round" stroke-linejoin="round"/>',
  'poutre-epaule':
    '<polyline class="se" points="-2,-56 -2,-4 3,-4" fill="none" stroke-width="8" stroke-linecap="round" stroke-linejoin="round"/><polyline class="se" points="2,-56 2,-4 7,-4" fill="none" stroke-width="8" stroke-linecap="round" stroke-linejoin="round"/><polyline class="se" points="0,-89 -3,-58" fill="none" stroke-width="7" stroke-linecap="round" stroke-linejoin="round"/><rect class="fe" x="-9" y="-97" width="18" height="45" rx="9"/><g transform="translate(-4 -101)"><g class="poutre-lance"><g transform="translate(4 101)"><rect class="se fi" x="-54" y="-105" width="100" height="8" rx="1" stroke-width="2"/><line class="se" x1="-44" y1="-101" x2="6" y2="-101" stroke-width="1" stroke-opacity="0.4" stroke-linecap="round"/></g></g></g><circle class="fe" cx="1" cy="-110" r="10"/>{L}<polyline class="si" points="1,-89 15,-80 12,-99" fill="none" stroke-width="10" stroke-linecap="round" stroke-linejoin="round"/><polyline class="se" points="1,-89 15,-80 12,-99" fill="none" stroke-width="7" stroke-linecap="round" stroke-linejoin="round"/>',
  'sautillement':
    '<polyline class="se" points="-2,-62 -3,-12 3,-4" fill="none" stroke-width="8" stroke-linecap="round" stroke-linejoin="round"/><polyline class="se" points="2,-62 1,-12 7,-4" fill="none" stroke-width="8" stroke-linecap="round" stroke-linejoin="round"/><polyline class="se" points="0,-95 -10,-67" fill="none" stroke-width="7" stroke-linecap="round" stroke-linejoin="round"/><rect class="fe" x="-9" y="-103" width="18" height="45" rx="9"/><circle class="fe" cx="1" cy="-116" r="10"/><g transform="translate(0 -6)">{L}</g><polyline class="si" points="1,-95 12,-67" fill="none" stroke-width="10" stroke-linecap="round" stroke-linejoin="round"/><polyline class="se" points="1,-95 12,-67" fill="none" stroke-width="7" stroke-linecap="round" stroke-linejoin="round"/>',
  'marteau-1':
    '<polyline class="se" points="-4,-56 -7,-4 -2,-4" fill="none" stroke-width="8" stroke-linecap="round" stroke-linejoin="round"/><polyline class="se" points="3,-56 6,-4 11,-4" fill="none" stroke-width="8" stroke-linecap="round" stroke-linejoin="round"/><polyline class="se" points="0,-89 -4,-58" fill="none" stroke-width="7" stroke-linecap="round" stroke-linejoin="round"/><rect class="fe" x="-9" y="-97" width="18" height="45" rx="9"/><circle class="fe" cx="1" cy="-110" r="10"/>{L}<g transform="translate(25 -75)"><g class="marteau-tour"><g transform="rotate(-100)"><line class="se" x1="-3" y1="0" x2="26" y2="0" stroke-width="4" stroke-linecap="round"/><rect class="fe" x="22" y="-8" width="8" height="15" rx="1.5"/></g></g></g><polyline class="si" points="1,-89 9,-69 25,-75" fill="none" stroke-width="10" stroke-linecap="round" stroke-linejoin="round"/><polyline class="se" points="1,-89 9,-69 25,-75" fill="none" stroke-width="7" stroke-linecap="round" stroke-linejoin="round"/>',
  'marteau-2':
    '<polyline class="se" points="-4,-56 -7,-4 -2,-4" fill="none" stroke-width="8" stroke-linecap="round" stroke-linejoin="round"/><polyline class="se" points="3,-56 6,-4 11,-4" fill="none" stroke-width="8" stroke-linecap="round" stroke-linejoin="round"/><polyline class="se" points="0,-89 -4,-58" fill="none" stroke-width="7" stroke-linecap="round" stroke-linejoin="round"/><rect class="fe" x="-9" y="-97" width="18" height="45" rx="9"/><circle class="fe" cx="1" cy="-110" r="10"/>{L}<g transform="translate(25 -75)"><g class="marteau-tour"><g transform="rotate(25)"><line class="se" x1="-3" y1="0" x2="26" y2="0" stroke-width="4" stroke-linecap="round"/><rect class="fe" x="22" y="-8" width="8" height="15" rx="1.5"/></g></g></g><polyline class="si" points="1,-89 9,-69 25,-75" fill="none" stroke-width="10" stroke-linecap="round" stroke-linejoin="round"/><polyline class="se" points="1,-89 9,-69 25,-75" fill="none" stroke-width="7" stroke-linecap="round" stroke-linejoin="round"/>',
} as const;

export type Pose = keyof typeof POSES;

export const LUNETTES =
  '<g class="lunettes"><line class="so" x1="5.6" y1="-111" x2="-5" y2="-109.5" stroke-width="1.6" stroke-linecap="round"/><circle class="so" cx="9" cy="-111" r="3.4" fill="none" stroke-width="1.8"/></g>';

export const OBJETS = {
  treteau:
    '<rect class="fe" x="-60" y="-58" width="120" height="6" rx="1"/><polyline class="se" points="-54,-2 -44,-53 -34,-2" fill="none" stroke-width="4" stroke-linecap="round" stroke-linejoin="round"/><line class="se" x1="-50.5" y1="-20" x2="-37.5" y2="-20" stroke-width="2.5" stroke-linecap="round"/><polyline class="se" points="34,-2 44,-53 54,-2" fill="none" stroke-width="4" stroke-linecap="round" stroke-linejoin="round"/><line class="se" x1="37.5" y1="-20" x2="50.5" y2="-20" stroke-width="2.5" stroke-linecap="round"/>',
  poutre:
    '<rect class="se fi" x="-50" y="-8" width="100" height="8" rx="1" stroke-width="2"/><line class="se" x1="-40" y1="-4" x2="10" y2="-4" stroke-width="1" stroke-opacity="0.4" stroke-linecap="round"/>',
  marteau:
    '<g transform="translate(0 0) rotate(0)"><line class="se" x1="-3" y1="0" x2="26" y2="0" stroke-width="4" stroke-linecap="round"/><rect class="fe" x="22" y="-8" width="8" height="15" rx="1.5"/></g>',
} as const;
